config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'accounts#index'
  resources :accounts, only:[:index, :create, :show, :destroy, :edit, :update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  validates :user, presence: true
  validates :title_id, presence: true,numericality: { other_than: 1 , message: "can't be blank"}
  
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user
  belongs_to :title
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/title.rb
class Title < ActiveHash::Base
  
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '食費(食材)' },
    { id: 3, name: 'ディナー' },
    { id: 4, name: 'カフェ' },
    { id: 5, name: 'ランチ' },
    { id: 6, name: '趣味、娯楽' },
    { id: 7, name: '交際費' },
    { id: 8, name: '交通費' },
    { id: 9, name: '美容' },
    { id: 10, name: '衣服' },
    { id: 11, name: '電気' },
    { id: 12, name: 'ガス' },
    { id: 13, name: '水道' },
    { id: 14, name: '通信費' },
    { id: 16, name: '家賃' },
    { id: 17, name: 'カーローン' },
    { id: 18, name: 'その他ローン' }
  ]

  include ActiveHash::Associations
  
  belongs_to :account

  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_user!, only: [:create,:edit,:destroy]




  def index
    @account = Account.new
    @accounts = Account.all


  end
  

  def create
    Account.create(account_params)
    redirect_to root_path
  end

  def show
    @account = Account.find(params[:id])
    @accounts = Account.all
  end

  def destroy
    @account = Account.find(params[:id])
    @account.destroy
    redirect_to root_path
  end

  def edit
    @account = Account.find(params[:id])
    @accounts = Account.all
  end

  def update
    @account = Account.find(params[:id])
    if @account.update(account_params)
      redirect_to root_path, notice: "編集しました"
    else
      render 'edit'
    end
  end


  private

  def account_params
    params.require(:account).permit(:title_id, :content, :start_time).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<div class="toppage">
<div class ="top-up">

<h1 class="top">Household account
    <div class ="user">
    <%if user_signed_in?%>
    <%= link_to 'ログアウト', "/", class: "login" %></li>
    <%=current_user.name%>
    <%else%>
    <%= link_to 'ログイン', "/", class: "login" %></li>
    <%= link_to '新規登録', "/", class: "sign-up" %></li>
    <%end%>
    </div>
   </h1>

<%= form_with(model: @account, local: true) do |form| %>

   <div class="title">
    <h class="form-tag">費用項目</h>
  <%= form.collection_select(:title_id, Title.all, :id, :name, {}) %>
</div>



  <div class="content">
    <h class="form-tag">金額</h>
    <%= form.text_field :content %>
  </div>

    <div class="time">
    <h class="form-tag">時間</h>
    <%= form.date_select :start_time %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>
<% end %>

<h class = "back">
<%= link_to '戻る', "/" %>
</h>


<div class="col-md-8">
<%= month_calendar events: @accounts do |date, accounts| %>
  <%= date.day %>

  <% accounts.each do |account| %>
      <%if current_user.id == account.user_id %>
    <div>
      <%= account.title.name%><h>：</h>
      <%= account.content.to_s(:delimited)%><h>円</h>

    </div>
  <% end %>
<% end %>
</div>
<%end%>

<div class="last">Household account</div>

app/views/accounts/index.html.erb
<div class="toppage">
<div class ="top-up">


   <h1 class="top">Household account
    <div class ="user">
    
    <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %>
    <%= current_user.name%>
    <%else%>
    <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
    <%= link_to 'ログイン', new_user_session_path, class: "login" %>
    <%end%>
    </div>
   </h1>
</div>
<br>

<div class="row">
<div class="col-md-4">


<%= form_with model:@account, local: true do |form| %>



  <div class="title">
    <h class="form-tag">費用項目</h>
  <%= form.collection_select(:title_id, Title.all, :id, :name, {}) %>
</div>


  <div class="content">
    <h class="form-tag">金額</h>
    <%= form.text_field :content %>
  </div>

  <div class="time">
    <h class="form-tag">日付</h>
    <%= form.date_select :start_time %>
  </div>

 <div class="submit">
    <%= form.submit "COUNT"%>
 </div>
<% end %>


</div>
<%i = 0%>
<%sum = []%>
<% @accounts.each do |account| %>
<%if user_signed_in? && current_user.id == account.user_id%>
 <%sum << account.content %>
 <%end%>
 <% i = i + 1%>
<% end %>

<h class="total">
累計出費金額：
<%=number_to_currency(sum.sum, :unit => "¥",:precision => 0)%>
</h>

<br>


<br>
<div class="col-md-8">
<%= month_calendar events: @accounts do |date, accounts| %>
  <%= date.day %>

  <%if user_signed_in?%>
  <% accounts.each do |account| %>
    <%if current_user.id == account.user_id %>
    <div>
      <%= link_to account.title.name, account_path(account.id) %><h>：</h>
      <%= link_to account.content.to_s(:delimited), account_path(account.id) %><h>円</h>
    </div>
    <%end%>
  <% end %>
 <% end %>


<% end %>
</div>
</div>
</div>

<div class="last">Household account</div>

app/views/accounts/show.html.erb
<div class="toppage">
<div class ="top-up">

<h1 class="top">Household account
    <div class ="user">
    <%if user_signed_in?%>
      <%= link_to 'ログアウト', "/", class: "login" %></li>
      <%= current_user.name%>
      <%else%>
      <%= link_to 'ログイン', "/", class: "login" %></li>
      <%= link_to '新規登録', "/", class: "sign-up" %></li>
      <%end%>
    </div>
   </h1>

<div class="show">
<div class="title">
    <h class="form-tag">費用項目：
      <%= @account.title.name %>
      </h>
</div>

<div class="content">
  <h class="form-tag">金額：
  <%= number_to_currency(@account.content, :unit =>"￥",:precision => 0) %>
  </h>
</div>

  <div class="time">
    <h class="form-tag">日付
  <%= @account.start_time.strftime("%m-%d") %>
  </h>
</div>

<%= link_to '編集', edit_account_path, class: "btn-edit"%>
<%= link_to '消去',account_path, method: :delete, data: { confirm: '本当に?' }, class: "btn-destroy"%>
<%= link_to '戻る', "/", class:"btn-back" %>
<br>


<%i = 0%>
<%sum = []%>
<% @accounts.each do |account| %>
<%if user_signed_in? && current_user.id == account.user_id%>
 <%sum << account.content %>
 <%end%>
 <% i = i + 1%>
<% end %>


<h class="total">
累計出費金額：
<%=number_to_currency(sum.sum, :unit => "¥",:precision => 0)%>
</h>




<div class="col-md-8">
<%= month_calendar events: @accounts do |date, accounts| %>
  <%= date.day %>

  <%if user_signed_in?%>
  <% accounts.each do |account| %>
    <%if current_user.id == account.user_id %>
    <div>
      <%= account.title.name%><h>：</h>
      <%= number_to_currency(account.content, :unit =>"￥",:precision => 0)%>

    </div>
  <% end %>
<% end %>
<%end%>
<%end%>
</div>
</div>

<div class="last">Household account</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HouseholdAccount</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>